# Copyright © Qualcomm Technologies, Inc. and/or its subsidiaries.
#
# SPDX-License-Identifier: BSD-3-Clause

interface virtio_iommu
local_include
base_module hyp/mem/useraccess
base_module hyp/vm/virtio
base_module hyp/vm/virtio_virtq
base_module hyp/vm/viommu
base_module hyp/platform/smmuv3

types virtio_iommu.tc
events virtio_iommu.ev
source hypercalls.c virtio_iommu.c vdevice.c virtio_virtq.c virtio_hw_probe.c
