# Copyright © Qualcomm Technologies, Inc. and/or its subsidiaries.
#
# SPDX-License-Identifier: BSD-3-Clause

interface vcpu

types vcpu.tc
events vcpu.ev
source vcpu.c

base_module hyp/core/vectors

arch_types aarch64 vcpu_aarch64.tc
arch_events aarch64 vcpu_aarch64.ev
arch_local_include aarch64
arch_source aarch64 sysreg_traps.c exception_inject.c reg_access.c wfi.c
arch_source aarch64 trap_dispatch.c aarch64_init.c context_switch.c
arch_events armv8-64 vcpu_aarch64.ev
arch_local_include armv8-64
arch_source armv8-64 vectors.S return.S pauth.c

arch_hypercalls aarch64 hypercalls.hvc
arch_source aarch64 hypercalls.c

arch_types aarch64 vfp_aarch64.tc
arch_events aarch64 vfp_aarch64.ev
arch_source aarch64 vfp.c
arch_template simple aarch64 vfp_save_load.c

arch_template simple armv8-64 vectors_tramp.S vectors_tramp.c

build_include cortex-a-v8_0
build_include cortex-a-v8_2
build_include cortex-a-v9
build_include neoverse-v1
build_include oryon-ncc
build_include qemu-armv8-5a-rng
