# Copyright © Qualcomm Technologies, Inc. and/or its subsidiaries.
#
# SPDX-License-Identifier: BSD-3-Clause

base_module hyp/vm/vgic
base_module hyp/vm/vic_base
base_module hyp/vm/vgic_its_base
base_module hyp/mem/useraccess
base_module hyp/platform/gicv3
source commands.c vits.c
configs GICV3_USE_VLPI=1
