# Copyright © Qualcomm Technologies, Inc. and/or its subsidiaries.
#
# SPDX-License-Identifier: BSD-3-Clause

interface arm_mte
events arm_vm_mte.ev
arch_types aarch64 arm_vm_mte_aarch64.tc
arch_source aarch64 arm_vm_mte.c
