# © 2021 Qualcomm Innovation Center, Inc. All rights reserved.
#
# SPDX-License-Identifier: BSD-3-Clause

interface watchdog
events watchdog.ev
types watchdog.tc
local_include
source watchdog.c watchdog_queue.c

configs VIRTUAL_WATCHDOG=1
