# Copyright © Qualcomm Technologies, Inc. and/or its subsidiaries.
#
# SPDX-License-Identifier: BSD-3-Clause

arch_source cortex-a-v9 sysreg_traps_cpu.c
arch_source cortex-a-v9 context_switch.c
arch_types cortex-a-v9 vcpu_aarch64.tc
