# © 2024 Qualcomm Innovation Center, Inc. All rights reserved.
#
# SPDX-License-Identifier: BSD-3-Clause

interface virtio_backend
base_module hyp/vm/virtio
types virtio_backend.tc
events virtio_backend.ev
source virtio_backend.c hypercalls.c
