# Copyright © Qualcomm Technologies, Inc. and/or its subsidiaries.
#
# SPDX-License-Identifier: BSD-3-Clause

interface memextent
local_include
events memextent.ev memextent_tests.ev
types memextent.tc memextent_tests.tc
source memextent.c memextent_basic.c memextent_tests.c hypercalls.c
