# Copyright © Qualcomm Technologies, Inc. and/or its subsidiaries.
#
# SPDX-License-Identifier: BSD-3-Clause

interface virtio_mmio
base_module hyp/vm/virtio
local_include
types virtio_mmio.tc
events virtio_mmio.ev
source virtio_mmio.c vdevice.c hypercalls.c
