# © 2022 Qualcomm Innovation Center, Inc. All rights reserved.
#
# SPDX-License-Identifier: BSD-3-Clause

local_include
base_module hyp/mem/memextent
events memextent_sparse.ev
types memextent_sparse.tc
source memextent_sparse.c memextent_tests.c
