# © 2021 Qualcomm Innovation Center, Inc. All rights reserved.
#
# SPDX-License-Identifier: BSD-3-Clause

interface watchdog
local_include
events watchdog.ev
types watchdog.tc
source watchdog.c hypercalls.c
