# Copyright © Qualcomm Technologies, Inc. and/or its subsidiaries.
#
# SPDX-License-Identifier: BSD-3-Clause

interface vpm
types vpm_base.tc
events vpm_base.ev
local_include
source hypercalls.c vpm_group.c
