# © 2024 Qualcomm Innovation Center, Inc. All rights reserved.
#
# SPDX-License-Identifier: BSD-3-Clause

interface range_tree
base_module hyp/misc/range_map_gpt
types range_tree_map.tc
events range_tree_map.ev
source range_tree_map.c
