# Copyright © Qualcomm Technologies, Inc. and/or its subsidiaries.
#
# SPDX-License-Identifier: BSD-3-Clause

local_include
types gicv3.tc
arch_types aarch64 gicv3-regs.tc
configs PLATFORM_HAS_MSI_TABLE=GICV3_HAS_LPI
configs PLATFORM_MSI_CONTROLLER_COUNT=PLATFORM_GITS_COUNT
arch_configs aarch64 AARCH64_ICC_REGS=1
template simple gich_lrs.h
first_class_object gicv3_its no_partition_create_hypcall
events gicv3.ev
source gicv3.c gicv3_its.c
events gicv3_tests.ev
types  gicv3_tests.tc
source gicv3_tests.c
