# Copyright © Qualcomm Technologies, Inc. and/or its subsidiaries.
#
# SPDX-License-Identifier: BSD-3-Clause

interface ffa

local_include
events ffa.ev
types ffa.tc
source ffa.c ffa_smc.c ffa_setup.c ffa_common.c ffa_vm_availability.c
source ffa_direct_msg.c ffa_rxtx.c ffa_memory.c
