# © 2021 Qualcomm Innovation Center, Inc. All rights reserved.
#
# SPDX-License-Identifier: BSD-3-Clause

interface cpulocal

assert_config (not 'PLATFORM_EXISTING_CORES' in configs) or (PLATFORM_EXISTING_CORES > 0)
assert_config (not 'PLATFORM_EXISTING_CORES' in configs) or (PLATFORM_MAX_CORES >= bin(PLATFORM_EXISTING_CORES).count("1"))

types cpulocal.tc
events cpulocal.ev
source cpulocal.c
