# Copyright © Qualcomm Technologies, Inc. and/or its subsidiaries.
#
# SPDX-License-Identifier: BSD-3-Clause

types arm_scheme_id_direct.tc
events arm_scheme_id_direct.ev
source arm_scheme_id_direct.c
