# Copyright © Qualcomm Technologies, Inc. and/or its subsidiaries.
#
# SPDX-License-Identifier: BSD-3-Clause

configs HYP_CONF_STR="gunyah"
platforms qemu fvp-rdv1

include featureset/gunyah-hyp

module vm/vcpu_run
module vm/virtio_pci
module vm/vpci
module vm/watchdog_null
arch_module armv8 vm/psci_pc
