# Copyright © Qualcomm Technologies, Inc. and/or its subsidiaries.
#
# SPDX-License-Identifier: BSD-3-Clause

guestapi_only

configs HYP_CONF_STR="gunyah"
platforms *

include featureset/gunyah-hyp

module vm/vcpu_run
module vm/virtio_input
module vm/virtio_mmio
module vm/virtio_pci
module vm/vrtc_pl031
module vm/vpci
module vm/watchdog_null

arch_module aarch64 platform/sdei_dispatcher
