// Automatically generated. Do not modify.
//
// Copyright © Qualcomm Technologies, Inc. and/or its subsidiaries.
//
// SPDX-License-Identifier: BSD-3-Clause

#ifndef HYPCONSTANTS_H_
#define HYPCONSTANTS_H_
// Struct and object member offsets

#define BACK_SIZE	4
#define BACK_ALIGN	1
#define OFS_BACK_K	0
#define OFS_BACK_P	1
#define OFS_BACK_TRI_TJ 2
#define OFS_BACK_TRI_TP 3

#define DEFAULT_SIZE  4
#define DEFAULT_ALIGN 4
#define OFS_DEFAULT_X 0

#define DEMO2U_SIZE	   16
#define DEMO2U_ALIGN	   8
#define OFS_DEMO2U_INT_VAR 0
#define OFS_DEMO2U_BIT_VAR 0

#define DEMOCONTAINER_SIZE			168
#define DEMOCONTAINER_ALIGN			8
#define OFS_DEMOCONTAINER_INT_VAR		0
#define OFS_DEMOCONTAINER_BIT_FIELD_VAR		8
#define OFS_DEMOCONTAINER_NESTED_STRUCT		24
#define OFS_DEMOCONTAINER_NESTED_STRUCT_INT_VAR 24

#define OFS_DEMOCONTAINER_NESTED_STRUCT2		    32
#define OFS_DEMOCONTAINER_NESTED_STRUCT2_START_VAR	    32
#define OFS_DEMOCONTAINER_NESTED_STRUCT2_CACHELINE_VAR	    96
#define OFS_DEMOCONTAINER_NESTED_STRUCT2_NEXT_CACHELINE_VAR 160

#define DEMOFIXED_SIZE			 136
#define DEMOFIXED_ALIGN			 8
#define OFS_DEMOFIXED_START_VAR		 0
#define OFS_DEMOFIXED_CACHELINE_VAR	 64
#define OFS_DEMOFIXED_NEXT_CACHELINE_VAR 128

#define DEMOPACKED_SIZE			     21
#define DEMOPACKED_ALIGN		     1
#define OFS_DEMOPACKED_INT_VAR		     0
#define OFS_DEMOPACKED_BIT_FIELD_VAR	     1
#define OFS_DEMOPACKED_NESTED_STRUCT	     17
#define OFS_DEMOPACKED_NESTED_STRUCT_INT_VAR 17

#define DEMOPACKEDINOBJECT_SIZE		     21
#define DEMOPACKEDINOBJECT_ALIGN	     1
#define OFS_DEMOPACKEDINOBJECT_INT_VAR	     0
#define OFS_DEMOPACKEDINOBJECT_BIT_FIELD_VAR 1
#define OFS_DEMOPACKEDINOBJECT_TT	     17

#define DEMOSINGLEFIELD_SIZE	    4
#define DEMOSINGLEFIELD_ALIGN	    4
#define OFS_DEMOSINGLEFIELD_INT_VAR 0

#define DEMOUSTRUCT_SIZE		       40
#define DEMOUSTRUCT_ALIGN		       8
#define OFS_DEMOUSTRUCT_INT_VAR		       0
#define OFS_DEMOUSTRUCT_BIT_FIELD_VAR	       8
#define OFS_DEMOUSTRUCT_EMBEDDED_UNION	       24
#define OFS_DEMOUSTRUCT_EMBEDDED_UNION_INT_VAR 24
#define OFS_DEMOUSTRUCT_EMBEDDED_UNION_BIT_VAR 24

#define EXECCONTEXT_SIZE		   2152
#define EXECCONTEXT_ALIGN		   8
#define OFS_EXECCONTEXT_O_MACHINE_E	   0
#define OFS_EXECCONTEXT_O_MACHINE_F	   1
#define OFS_EXECCONTEXT_MACHINE_E	   2
#define OFS_EXECCONTEXT_MACHINE_F	   3
#define OFS_EXECCONTEXT_O_BIT_FIELD_IN_OBJ 8
#define OFS_EXECCONTEXT_TT		   24
#define OFS_EXECCONTEXT_A		   32
#define OFS_EXECCONTEXT_B		   36
#define OFS_EXECCONTEXT_O_O		   40
#define OFS_EXECCONTEXT_O_P		   44
#define OFS_EXECCONTEXT_O_J(n)		   (48U + (4U * (n)))
#define OFS_EXECCONTEXT_O_JJ(n)		   (88U + (8U * (n)))
#define OFS_EXECCONTEXT_O_N_T		   168
#define OFS_EXECCONTEXT_O_N_UY		   172
#define OFS_EXECCONTEXT_O_OO_T		   176
#define OFS_EXECCONTEXT_O_OO_UY		   180
#define OFS_EXECCONTEXT_T		   184
#define OFS_EXECCONTEXT_UY		   188
#define OFS_EXECCONTEXT_PERMITTED_OFFSET   2048
#define OFS_EXECCONTEXT_O_DS		   2052
#define OFS_EXECCONTEXT_O_DS_INT_VAR	   2052
#define OFS_EXECCONTEXT_O_DS_BIT_FIELD_VAR 2053
#define OFS_EXECCONTEXT_O_DS_TT		   2069

#define OFS_EXECCONTEXT_YY(n) (2073U + (4U * (n)))
#define OFS_EXECCONTEXT_JJ(n) (2105U + (4U * (n)))

#define NESTUI_SIZE   8
#define NESTUI_ALIGN  4
#define OFS_NESTUI_T  0
#define OFS_NESTUI_UY 4

#define STANDALONE_SIZE	 2
#define STANDALONE_ALIGN 1
#define OFS_STANDALONE_T 0
#define OFS_STANDALONE_U 1

#define DEVICE_DESCRIPTOR_SIZE	      16
#define DEVICE_DESCRIPTOR_ALIGN	      8
#define OFS_DEVICE_DESCRIPTOR_COLOR   0
#define OFS_DEVICE_DESCRIPTOR_CONTROL 8

#define SIZEOF_TEST_SIZE     4
#define SIZEOF_TEST_ALIGN    4
#define OFS_SIZEOF_TEST_TEST 0

#define TEST_STRUCT_SIZE		   168
#define TEST_STRUCT_ALIGN		   8
#define OFS_TEST_STRUCT_TEST_BITMAP_512(n) (0U + (8U * (n)))
#define OFS_TEST_STRUCT_TEST_BITMAP_768(n) (64U + (8U * (n)))
#define OFS_TEST_STRUCT_TEST_BITMAP_1(n)   (160U + (8U * (n)))

// Enumeration constants

#define ENUM_COLOR_CODE_RED  1
#define ENUM_COLOR_CODE_BLUE 2

#define ENUM_COLOR_CODE_MIN_VALUE (1)
#define ENUM_COLOR_CODE_MAX_VALUE (2)

#define ENUM_ERROR_CODE_ERROR_OK		0
#define ENUM_ERROR_CODE_ERROR_RETRY		1
#define ENUM_ERROR_CODE_ERROR_INVALID_ARG	2
#define ENUM_ERROR_CODE_ERROR_TIMEOUT		-3
#define ENUM_ERROR_CODE_ERROR_RESOURCE_BUSY	-2
#define ENUM_ERROR_CODE_ERROR_NOT_FOUND		-1
#define ENUM_ERROR_CODE_ERROR_FATAL		10
#define ENUM_ERROR_CODE_ERROR_PERMISSION_DENIED 11
#define ENUM_ERROR_CODE_ERROR_OUT_OF_MEMORY	12

#define ENUM_ERROR_CODE_MIN_VALUE (-3)
#define ENUM_ERROR_CODE_MAX_VALUE (12)

#define ENUM_PRIORITY_LEVEL_LOW	   0
#define ENUM_PRIORITY_LEVEL_MEDIUM 1
#define ENUM_PRIORITY_LEVEL_HIGH   2

#define ENUM_PRIORITY_LEVEL_MIN_VALUE (0)
#define ENUM_PRIORITY_LEVEL_MAX_VALUE (2)

#define ENUM_RESULT_CODE_RESULT_SUCCESS 1
#define ENUM_RESULT_CODE_RESULT_FAILURE 2

#define ENUM_RESULT_CODE_MIN_VALUE (1)
#define ENUM_RESULT_CODE_MAX_VALUE (2)

#define ENUM_STATUS_FLAG_INACTIVE 0
#define ENUM_STATUS_FLAG_ACTIVE	  1
#define ENUM_STATUS_FLAG_PENDING  2

#define ENUM_STATUS_FLAG_MIN_VALUE (0)
#define ENUM_STATUS_FLAG_MAX_VALUE (2)

#define ENUM_TEMPERATURE_OFFSET_TEMP_ZERO  0
#define ENUM_TEMPERATURE_OFFSET_TEMP_BELOW -1
#define ENUM_TEMPERATURE_OFFSET_TEMP_ABOVE 1

#define ENUM_TEMPERATURE_OFFSET_MIN_VALUE (-1)
#define ENUM_TEMPERATURE_OFFSET_MAX_VALUE (1)

// Bitfield shifts and masks

#define STRUCTBITFIELD_TEST_SHIFT     (0U)
#define STRUCTBITFIELD_TEST_BITS      (32U)
#define STRUCTBITFIELD_TEST_MASK      (0xffffffffU)
#define STRUCTBITFIELD_TEST_PRESHIFT  (0U)
#define STRUCTBITFIELD_TEST1_SHIFT    (32U)
#define STRUCTBITFIELD_TEST1_BITS     (11U)
#define STRUCTBITFIELD_TEST1_MASK     (0x7ff00000000U)
#define STRUCTBITFIELD_TEST1_PRESHIFT (0U)
#define STRUCTBITFIELD_TEST5_SHIFT    (51U)
#define STRUCTBITFIELD_TEST5_BITS     (8U)
#define STRUCTBITFIELD_TEST5_MASK     (0x7f8000000000000U)
#define STRUCTBITFIELD_TEST5_PRESHIFT (0U)

#define TEST_COMB_FEAT_VAR_VAR1_VALUE_SHIFT    (0U)
#define TEST_COMB_FEAT_VAR_VAR1_VALUE_BITS     (64U)
#define TEST_COMB_FEAT_VAR_VAR1_VALUE_MASK     (0xffffffffffffffffU)
#define TEST_COMB_FEAT_VAR_VAR1_VALUE_PRESHIFT (0U)

#define TEST_COMB_FEAT_VAR_VAR2_VALUE_SHIFT    (0U)
#define TEST_COMB_FEAT_VAR_VAR2_VALUE_BITS     (64U)
#define TEST_COMB_FEAT_VAR_VAR2_VALUE_MASK     (0xffffffffffffffffU)
#define TEST_COMB_FEAT_VAR_VAR2_VALUE_PRESHIFT (0U)

#define TEST_COMB_MULTI_OVER_VAR1_VALUE_SHIFT	 (0U)
#define TEST_COMB_MULTI_OVER_VAR1_VALUE_BITS	 (64U)
#define TEST_COMB_MULTI_OVER_VAR1_VALUE_MASK	 (0xffffffffffffffffU)
#define TEST_COMB_MULTI_OVER_VAR1_VALUE_PRESHIFT (0U)

#define TEST_COMB_MULTI_OVER_VAR2_VALUE_SHIFT	 (0U)
#define TEST_COMB_MULTI_OVER_VAR2_VALUE_BITS	 (64U)
#define TEST_COMB_MULTI_OVER_VAR2_VALUE_MASK	 (0xffffffffffffffffU)
#define TEST_COMB_MULTI_OVER_VAR2_VALUE_PRESHIFT (0U)

#define TEST_DEFAULT_FEAT_VALUE_SHIFT	 (0U)
#define TEST_DEFAULT_FEAT_VALUE_BITS	 (64U)
#define TEST_DEFAULT_FEAT_VALUE_MASK	 (0xffffffffffffffffU)
#define TEST_DEFAULT_FEAT_VALUE_PRESHIFT (0U)

#define TEST_DEFAULT_PLAIN_VALUE_SHIFT	  (0U)
#define TEST_DEFAULT_PLAIN_VALUE_BITS	  (64U)
#define TEST_DEFAULT_PLAIN_VALUE_MASK	  (0xffffffffffffffffU)
#define TEST_DEFAULT_PLAIN_VALUE_PRESHIFT (0U)

#define TESTBITFIELD_TEST_SHIFT	    (0U)
#define TESTBITFIELD_TEST_BITS	    (32U)
#define TESTBITFIELD_TEST_MASK	    (0xffffffffU)
#define TESTBITFIELD_TEST_PRESHIFT  (0U)
#define TESTBITFIELD_TEST1_SHIFT    (32U)
#define TESTBITFIELD_TEST1_BITS	    (11U)
#define TESTBITFIELD_TEST1_MASK	    (0x7ff00000000U)
#define TESTBITFIELD_TEST1_PRESHIFT (0U)
#define TESTBITFIELD_TEST5_SHIFT    (43U)
#define TESTBITFIELD_TEST5_BITS	    (8U)
#define TESTBITFIELD_TEST5_MASK	    (0x7f80000000000U)
#define TESTBITFIELD_TEST5_PRESHIFT (0U)

#define UBITFIELD_TEST_SHIFT	 (0U)
#define UBITFIELD_TEST_BITS	 (32U)
#define UBITFIELD_TEST_MASK	 (0xffffffffU)
#define UBITFIELD_TEST_PRESHIFT	 (0U)
#define UBITFIELD_TEST1_SHIFT	 (32U)
#define UBITFIELD_TEST1_BITS	 (11U)
#define UBITFIELD_TEST1_MASK	 (0x7ff00000000U)
#define UBITFIELD_TEST1_PRESHIFT (0U)
#define UBITFIELD_TEST5_SHIFT	 (51U)
#define UBITFIELD_TEST5_BITS	 (8U)
#define UBITFIELD_TEST5_MASK	 (0x7f8000000000000U)
#define UBITFIELD_TEST5_PRESHIFT (0U)

#define AUTO_LAYOUT_REGISTER_AUTO_FIELD_5BIT_SHIFT	    (0U)
#define AUTO_LAYOUT_REGISTER_AUTO_FIELD_5BIT_BITS	    (5U)
#define AUTO_LAYOUT_REGISTER_AUTO_FIELD_5BIT_MASK	    (0x1fU)
#define AUTO_LAYOUT_REGISTER_AUTO_FIELD_5BIT_PRESHIFT	    (0U)
#define AUTO_LAYOUT_REGISTER_AUTO_FIELD_ENUM_SHIFT	    (5U)
#define AUTO_LAYOUT_REGISTER_AUTO_FIELD_ENUM_BITS	    (2U)
#define AUTO_LAYOUT_REGISTER_AUTO_FIELD_ENUM_MASK	    (0x60U)
#define AUTO_LAYOUT_REGISTER_AUTO_FIELD_ENUM_PRESHIFT	    (0U)
#define AUTO_LAYOUT_REGISTER_REPLACEMENT_FIELD_SHIFT	    (8U)
#define AUTO_LAYOUT_REGISTER_REPLACEMENT_FIELD_BITS	    (8U)
#define AUTO_LAYOUT_REGISTER_REPLACEMENT_FIELD_MASK	    (0xff00U)
#define AUTO_LAYOUT_REGISTER_REPLACEMENT_FIELD_PRESHIFT	    (0U)
#define AUTO_LAYOUT_REGISTER_ADDITIONAL_AUTO_FIELD_SHIFT    (16U)
#define AUTO_LAYOUT_REGISTER_ADDITIONAL_AUTO_FIELD_BITS	    (8U)
#define AUTO_LAYOUT_REGISTER_ADDITIONAL_AUTO_FIELD_MASK	    (0xff0000U)
#define AUTO_LAYOUT_REGISTER_ADDITIONAL_AUTO_FIELD_PRESHIFT (0U)

#define INITIALIZATION_REGISTER_RESET_FLAG_SHIFT	 (7U)
#define INITIALIZATION_REGISTER_RESET_FLAG_BITS		 (1U)
#define INITIALIZATION_REGISTER_RESET_FLAG_MASK		 (0x80U)
#define INITIALIZATION_REGISTER_RESET_FLAG_PRESHIFT	 (0U)
#define INITIALIZATION_REGISTER_MAGIC_BYTE_B_SHIFT	 (8U)
#define INITIALIZATION_REGISTER_MAGIC_BYTE_B_BITS	 (8U)
#define INITIALIZATION_REGISTER_MAGIC_BYTE_B_MASK	 (0xff00U)
#define INITIALIZATION_REGISTER_MAGIC_BYTE_B_PRESHIFT	 (0U)
#define INITIALIZATION_REGISTER_MAGIC_BYTE_C_SHIFT	 (16U)
#define INITIALIZATION_REGISTER_MAGIC_BYTE_C_BITS	 (8U)
#define INITIALIZATION_REGISTER_MAGIC_BYTE_C_MASK	 (0xff0000U)
#define INITIALIZATION_REGISTER_MAGIC_BYTE_C_PRESHIFT	 (0U)
#define INITIALIZATION_REGISTER_EXTENDED_CONFIG_SHIFT	 (40U)
#define INITIALIZATION_REGISTER_EXTENDED_CONFIG_BITS	 (8U)
#define INITIALIZATION_REGISTER_EXTENDED_CONFIG_MASK	 (0xff0000000000U)
#define INITIALIZATION_REGISTER_EXTENDED_CONFIG_PRESHIFT (0U)

#define INTERRUPT_CONTROL_REGISTER_INTERRUPT_ID_SHIFT	    (0U)
#define INTERRUPT_CONTROL_REGISTER_INTERRUPT_ID_BITS	    (8U)
#define INTERRUPT_CONTROL_REGISTER_INTERRUPT_ID_MASK	    (0xffU)
#define INTERRUPT_CONTROL_REGISTER_INTERRUPT_ID_PRESHIFT    (0U)
#define INTERRUPT_CONTROL_REGISTER_PRIORITY_LEVEL_SHIFT	    (8U)
#define INTERRUPT_CONTROL_REGISTER_PRIORITY_LEVEL_BITS	    (8U)
#define INTERRUPT_CONTROL_REGISTER_PRIORITY_LEVEL_MASK	    (0xff00U)
#define INTERRUPT_CONTROL_REGISTER_PRIORITY_LEVEL_PRESHIFT  (0U)
#define INTERRUPT_CONTROL_REGISTER_HANDLER_INDEX_SHIFT	    (16U)
#define INTERRUPT_CONTROL_REGISTER_HANDLER_INDEX_BITS	    (8U)
#define INTERRUPT_CONTROL_REGISTER_HANDLER_INDEX_MASK	    (0xff0000U)
#define INTERRUPT_CONTROL_REGISTER_HANDLER_INDEX_PRESHIFT   (0U)
#define INTERRUPT_CONTROL_REGISTER_INTERRUPT_FLAGS_SHIFT    (32U)
#define INTERRUPT_CONTROL_REGISTER_INTERRUPT_FLAGS_BITS	    (4U)
#define INTERRUPT_CONTROL_REGISTER_INTERRUPT_FLAGS_MASK	    (0xf00000000U)
#define INTERRUPT_CONTROL_REGISTER_INTERRUPT_FLAGS_PRESHIFT (0U)

#define MEMORY_CONFIG_REGISTER_BASE_ADDRESS_SHIFT	 (0U)
#define MEMORY_CONFIG_REGISTER_BASE_ADDRESS_BITS	 (8U)
#define MEMORY_CONFIG_REGISTER_BASE_ADDRESS_MASK	 (0xffU)
#define MEMORY_CONFIG_REGISTER_BASE_ADDRESS_PRESHIFT	 (0U)
#define MEMORY_CONFIG_REGISTER_READ_ONLY_ID_SHIFT	 (16U)
#define MEMORY_CONFIG_REGISTER_READ_ONLY_ID_BITS	 (8U)
#define MEMORY_CONFIG_REGISTER_READ_ONLY_ID_MASK	 (0xff0000U)
#define MEMORY_CONFIG_REGISTER_READ_ONLY_ID_PRESHIFT	 (0U)
#define MEMORY_CONFIG_REGISTER_EXTENDED_ADDRESS_SHIFT	 (24U)
#define MEMORY_CONFIG_REGISTER_EXTENDED_ADDRESS_BITS	 (40U)
#define MEMORY_CONFIG_REGISTER_EXTENDED_ADDRESS_MASK	 (0xffffffffff000000U)
#define MEMORY_CONFIG_REGISTER_EXTENDED_ADDRESS_PRESHIFT (0U)

#define MODULE_CONFIG_REGISTER_EXTENDED_MODULE_ID_SHIFT	      (0U)
#define MODULE_CONFIG_REGISTER_EXTENDED_MODULE_ID_BITS	      (8U)
#define MODULE_CONFIG_REGISTER_EXTENDED_MODULE_ID_MASK	      (0xffU)
#define MODULE_CONFIG_REGISTER_EXTENDED_MODULE_ID_PRESHIFT    (0U)
#define MODULE_CONFIG_REGISTER_MODULE_VERSION_SHIFT	      (8U)
#define MODULE_CONFIG_REGISTER_MODULE_VERSION_BITS	      (8U)
#define MODULE_CONFIG_REGISTER_MODULE_VERSION_MASK	      (0xff00U)
#define MODULE_CONFIG_REGISTER_MODULE_VERSION_PRESHIFT	      (0U)
#define MODULE_CONFIG_REGISTER_FEATURE_FLAGS_SHIFT	      (16U)
#define MODULE_CONFIG_REGISTER_FEATURE_FLAGS_BITS	      (5U)
#define MODULE_CONFIG_REGISTER_FEATURE_FLAGS_MASK	      (0x1f0000U)
#define MODULE_CONFIG_REGISTER_FEATURE_FLAGS_PRESHIFT	      (0U)
#define MODULE_CONFIG_REGISTER_CAPABILITY_BITS_SHIFT	      (21U)
#define MODULE_CONFIG_REGISTER_CAPABILITY_BITS_BITS	      (32U)
#define MODULE_CONFIG_REGISTER_CAPABILITY_BITS_MASK	      (0x1fffffffe00000U)
#define MODULE_CONFIG_REGISTER_CAPABILITY_BITS_PRESHIFT	      (0U)
#define MODULE_CONFIG_REGISTER_ADDITIONAL_CAPABILITY_SHIFT    (53U)
#define MODULE_CONFIG_REGISTER_ADDITIONAL_CAPABILITY_BITS     (8U)
#define MODULE_CONFIG_REGISTER_ADDITIONAL_CAPABILITY_MASK     (0x1fe0000000000000U)
#define MODULE_CONFIG_REGISTER_ADDITIONAL_CAPABILITY_PRESHIFT (0U)

#define PERIPHERAL_CONTROL_REGISTER_PERIPHERAL_ID_SHIFT	   (0U)
#define PERIPHERAL_CONTROL_REGISTER_PERIPHERAL_ID_BITS	   (8U)
#define PERIPHERAL_CONTROL_REGISTER_PERIPHERAL_ID_MASK	   (0xffU)
#define PERIPHERAL_CONTROL_REGISTER_PERIPHERAL_ID_PRESHIFT (0U)
#define PERIPHERAL_CONTROL_REGISTER_VERSION_SHIFT	   (16U)
#define PERIPHERAL_CONTROL_REGISTER_VERSION_BITS	   (8U)
#define PERIPHERAL_CONTROL_REGISTER_VERSION_MASK	   (0xff0000U)
#define PERIPHERAL_CONTROL_REGISTER_VERSION_PRESHIFT	   (0U)
#define PERIPHERAL_CONTROL_REGISTER_CONFIG_DATA_SHIFT	   (24U)
#define PERIPHERAL_CONTROL_REGISTER_CONFIG_DATA_BITS	   (40U)
#define PERIPHERAL_CONTROL_REGISTER_CONFIG_DATA_MASK	   (0xffffffffff000000U)
#define PERIPHERAL_CONTROL_REGISTER_CONFIG_DATA_PRESHIFT   (0U)

#define SYSTEM_CONTROL_REGISTER_DEVICE_ID_SHIFT		(0U)
#define SYSTEM_CONTROL_REGISTER_DEVICE_ID_BITS		(8U)
#define SYSTEM_CONTROL_REGISTER_DEVICE_ID_MASK		(0xffU)
#define SYSTEM_CONTROL_REGISTER_DEVICE_ID_PRESHIFT	(0U)
#define SYSTEM_CONTROL_REGISTER_PRIORITY_SHIFT		(8U)
#define SYSTEM_CONTROL_REGISTER_PRIORITY_BITS		(8U)
#define SYSTEM_CONTROL_REGISTER_PRIORITY_MASK		(0xff00U)
#define SYSTEM_CONTROL_REGISTER_PRIORITY_PRESHIFT	(0U)
#define SYSTEM_CONTROL_REGISTER_STATUS_CODE_SHIFT	(16U)
#define SYSTEM_CONTROL_REGISTER_STATUS_CODE_BITS	(4U)
#define SYSTEM_CONTROL_REGISTER_STATUS_CODE_MASK	(0xf0000U)
#define SYSTEM_CONTROL_REGISTER_STATUS_CODE_PRESHIFT	(0U)
#define SYSTEM_CONTROL_REGISTER_FLAGS_SHIFT		(20U)
#define SYSTEM_CONTROL_REGISTER_FLAGS_BITS		(6U)
#define SYSTEM_CONTROL_REGISTER_FLAGS_MASK		(0x3f00000U)
#define SYSTEM_CONTROL_REGISTER_FLAGS_PRESHIFT		(0U)
#define SYSTEM_CONTROL_REGISTER_MODE_SHIFT		(26U)
#define SYSTEM_CONTROL_REGISTER_MODE_BITS		(6U)
#define SYSTEM_CONTROL_REGISTER_MODE_MASK		(0xfc000000U)
#define SYSTEM_CONTROL_REGISTER_MODE_PRESHIFT		(0U)
#define SYSTEM_CONTROL_REGISTER_ADDRESS_OFFSET_SHIFT	(40U)
#define SYSTEM_CONTROL_REGISTER_ADDRESS_OFFSET_BITS	(4U)
#define SYSTEM_CONTROL_REGISTER_ADDRESS_OFFSET_MASK	(0xf0000000000U)
#define SYSTEM_CONTROL_REGISTER_ADDRESS_OFFSET_PRESHIFT (12U)
#define SYSTEM_CONTROL_REGISTER_ENABLE_SHIFT		(48U)
#define SYSTEM_CONTROL_REGISTER_ENABLE_BITS		(1U)
#define SYSTEM_CONTROL_REGISTER_ENABLE_MASK		(0x1000000000000U)
#define SYSTEM_CONTROL_REGISTER_ENABLE_PRESHIFT		(0U)
#define SYSTEM_CONTROL_REGISTER_LOCK_BIT_SHIFT		(49U)
#define SYSTEM_CONTROL_REGISTER_LOCK_BIT_BITS		(1U)
#define SYSTEM_CONTROL_REGISTER_LOCK_BIT_MASK		(0x2000000000000U)
#define SYSTEM_CONTROL_REGISTER_LOCK_BIT_PRESHIFT	(0U)
#define SYSTEM_CONTROL_REGISTER_SIGN_BIT_SHIFT		(50U)
#define SYSTEM_CONTROL_REGISTER_SIGN_BIT_BITS		(1U)
#define SYSTEM_CONTROL_REGISTER_SIGN_BIT_MASK		(0x4000000000000U)
#define SYSTEM_CONTROL_REGISTER_SIGN_BIT_PRESHIFT	(0U)

#if defined(__ASSEMBLER__)
// Untyped constants (assembly only)

#define ARRAY_SIZE	    10	  // 0xa
#define CSZ		    2	  // 0x2
#define LOGICAL_AND_TEST    1	  // 0x1
#define LOGICAL_OR_TEST	    0	  // 0x0
#define PAGE_SIZE	    4096  // 0x1000
#define SIZEOF_MINUSES_TEST 4092  // 0xffc
#define SIZEOF_MINUS_TEST   4092  // 0xffc
#define UNARY_MINUS_TEST    -4096 // -0x1000

#endif // defined(__ASSEMBLER__)
#else
#error HYPCONSTANTS_H_ multiple include
#endif
