# Copyright © Qualcomm Technologies, Inc. and/or its subsidiaries.
#
# SPDX-License-Identifier: BSD-3-Clause

interface arm_mpam
types arm_vm_mpam.tc
events arm_vm_mpam.ev
arch_types aarch64 arm_vm_mpam_aarch64.tc
arch_source aarch64 arm_vm_mpam.c
