# Copyright © Qualcomm Technologies, Inc. and/or its subsidiaries.
#
# SPDX-License-Identifier: BSD-3-Clause

configs VERBOSE=1
configs VERBOSE_TRACE=1
configs RESET_ON_ABORT=0
configs HYP_QUALITY="debug"
configs ROOTVM_ALWAYS_ON_BOOT_CORE=1
flags -O1 -g -mstrict-align -fsanitize=undefined -fsanitize-trap=undefined

#include include/debug_no_kaslr
include include/debug_no_cspace_rand
include include/debug_no_rootvm_aslr
