# Copyright © Qualcomm Technologies, Inc. and/or its subsidiaries.
#
# SPDX-License-Identifier: BSD-3-Clause

# Uncomment for additional traces
# configs VERBOSE_TRACE=1
configs RESET_ON_ABORT=1
configs HYP_QUALITY="prod"
flags -flto -O3 -g
