# Copyright © Qualcomm Technologies, Inc. and/or its subsidiaries.
#
# SPDX-License-Identifier: BSD-3-Clause

is_abi
# Use the Linux target because it knows how to link with LLD
target_triple aarch64-linux-gnu
defines_link
flags -mgeneral-regs-only -mtp=el2 -mno-outline-atomics
configs ARCH_IS_64BIT=1 ARCH_ENDIAN_LITTLE=1
includes

configs ARCH_SANITIZE_STACK_SIZE=1536U
quality_configs_override production ARCH_SANITIZE_STACK_SIZE=1024
quality_configs_override production-unchecked ARCH_SANITIZE_STACK_SIZE=1024

quality_configs codecoverage VCPU_MIN_STACK_SIZE=8192U
quality_configs debug VCPU_MIN_STACK_SIZE=8192U
