# © 2021 Qualcomm Innovation Center, Inc. All rights reserved.
#
# SPDX-License-Identifier: BSD-3-Clause

base_arch cortex-a-v8_2
flags -mcpu=cortex-a78c
configs ARCH_CORE_IDS=CORTEX_A78C
configs ARCH_ARM_FEAT_VMID16=1
configs ARCH_ARM_PMU_HPMN_UNPREDICTABLE=1

configs ARCH_ARM_FEAT_PMUv3p1=1
configs ARCH_ARM_FEAT_IESB=1
configs ARCH_ARM_FEAT_HPDS2=1
# Added features in A78C vs A78
configs ARCH_ARM_FEAT_LSE2=1
configs ARCH_ARM_FEAT_PAuth=1
configs ARCH_ARM_FEAT_PAuth2=1
flags -mbranch-protection=pac-ret

# FIXME:
configs VGIC_HAS_EXT_SPIS=1
configs VGIC_HAS_EXT_PPIS=0
configs VGIC_EMULATE_EXT_RANGE=1
configs PLATFORM_VGIC_SPI_EXT_LIMIT=1024
