# Copyright © Qualcomm Technologies, Inc. and/or its subsidiaries.
#
# SPDX-License-Identifier: BSD-3-Clause

base_arch cortex-a-v8_2
flags -mcpu=cortex-a77
configs ARCH_CORE_IDS=CORTEX_A55,CORTEX_A77

configs ARCH_AARCH64_BIG_END_ALL_CORES=1

configs ARCH_ARM_FEAT_VMID16=1
configs ARCH_ARM_PMU_HPMN_UNPREDICTABLE=1

configs ARCH_ARM_FEAT_PMUv3p1=1
configs ARCH_ARM_FEAT_IESB=1
configs ARCH_ARM_FEAT_HPDS2=1

# Some ARM CPUs without explicit extended SPI support coupled with a GIC
# supporting them don't work properly. ARM Cortex-A55 requires emulation as
# the last 4 Ext SPIs don't work through the GICV. For ARM CPUs that we want
# extended vSPI support for but have a similar limitation, we can configure
# VGIC_EMULATE_EXT_RANGE=1 but it is not necessary if we've disabled extended
# SPIs.
# FIXME: QC Gunyah issue #223
configs VGIC_HAS_EXT_SPIS=0
configs VGIC_HAS_EXT_PPIS=0
