# © 2021 Qualcomm Innovation Center, Inc. All rights reserved.
#
# SPDX-License-Identifier: BSD-3-Clause

base_arch cortex-a-v8_2
flags -mcpu=cortex-a55
configs ARCH_CORE_IDS=CORTEX_A55
configs ARCH_ARM_FEAT_VMID16=1
configs ARCH_ARM_PMU_HPMN_UNPREDICTABLE=1

configs ARCH_ARM_FEAT_PMUv3p1=1
configs ARCH_ARM_FEAT_IESB=1
configs ARCH_ARM_FEAT_HPDS2=1

# Some ARM CPUs without explicit extended SPI support coupled with a GIC
# supporting them don't work properly. ARM Cortex-A55 requires emulation as
# the last 4 Ext SPIs don't work through the GICV. For ARM CPUs that we want
# extended vSPI support for but have a similar limitation, we can configure
# VGIC_EMULATE_EXT_RANGE=1 but it is not necessary if we've disabled extended
# SPIs. For A55, reducing the limit by 32 to exclude the last 4 non-functoning
# IRQ(which makes the limit set to 992) since GIC implementations can choose
# to implement any multiple of 32 IRQs.
configs VGIC_HAS_EXT_SPIS=1
configs PLATFORM_VGIC_SPI_EXT_LIMIT=992
configs VGIC_HAS_EXT_PPIS=0
configs VGIC_EMULATE_EXT_RANGE=1
