# Copyright © Qualcomm Technologies, Inc. and/or its subsidiaries.
#
# SPDX-License-Identifier: BSD-3-Clause

base_arch armv9

# BTI and PAuth are mandatory in v9.0, so tell the compiler to use them
flags -mbranch-protection=bti+pac-ret

# Mandatory architecture extensions in v9.0
configs ARCH_ARM_FEAT_CTIV2=1
configs ARCH_ARM_FEAT_CSV2=1
configs ARCH_ARM_FEAT_CSV3=1
configs ARCH_ARM_FEAT_SB=1
configs ARCH_ARM_FEAT_SSBS=1
configs ARCH_ARM_FEAT_SPECRES=1

configs ARCH_ARM_FEAT_HPDS=1
configs ARCH_ARM_FEAT_LSE=1
configs ARCH_ARM_FEAT_LOR=1
configs ARCH_ARM_FEAT_PAN=1
configs ARCH_ARM_FEAT_RDM=1
configs ARCH_ARM_FEAT_VHE=1
configs ARCH_ARM_FEAT_CRC32=1

configs ARCH_ARM_FEAT_ASMv8p2=1
configs ARCH_ARM_FEAT_PAN2=1
configs ARCH_ARM_FEAT_DPB2=1
configs ARCH_ARM_FEAT_DPB=1
configs ARCH_ARM_FEAT_DEBUGv8p2=1
configs ARCH_ARM_FEAT_DotProd=1
configs ARCH_ARM_FEAT_EVT=1
configs ARCH_ARM_FEAT_FHM=1
configs ARCH_ARM_FEAT_FP16=1
configs ARCH_ARM_FEAT_IESB=1
configs ARCH_ARM_FEAT_RAS=1
configs ARCH_ARM_FEAT_TTCNP=1
configs ARCH_ARM_FEAT_XNX=1
configs ARCH_ARM_FEAT_UAO=1

configs ARCH_ARM_FEAT_DoPD=1
configs ARCH_ARM_FEAT_FCMA=1
configs ARCH_ARM_FEAT_FPAC=1
configs ARCH_ARM_FEAT_JSCVT=1
configs ARCH_ARM_FEAT_PAuth=1
configs ARCH_ARM_FEAT_LRCPC=1

configs ARCH_ARM_FEAT_FlagM=1
configs ARCH_ARM_FEAT_DEBUGv8p4=1
configs ARCH_ARM_FEAT_DoubleFault=1
configs ARCH_ARM_FEAT_DIT=1
configs ARCH_ARM_FEAT_IDST=1
configs ARCH_ARM_FEAT_LSE2=1
configs ARCH_ARM_FEAT_RASv1p1=1
configs ARCH_ARM_FEAT_LRCPC2=1
configs ARCH_ARM_FEAT_S2FWB=1
configs ARCH_ARM_FEAT_TRF=1
configs ARCH_ARM_FEAT_TLBIOS=1
configs ARCH_ARM_FEAT_TLBIRANGE=1
configs ARCH_ARM_FEAT_TTL=1
configs ARCH_ARM_FEAT_TTST=1
configs ARCH_ARM_FEAT_BBM=1

configs ARCH_ARM_FEAT_BTI=1
configs ARCH_ARM_FEAT_CMODX=1
configs ARCH_ARM_FEAT_FlagM2=1
configs ARCH_ARM_FEAT_E0PD=1
configs ARCH_ARM_FEAT_FRINTTS=1
configs ARCH_ARM_FEAT_GTG=1

configs ARCH_AARCH64_ASID16=1 ARCH_ARM_PMU_VER=3

# The number of implemented ICH_LR<n>_EL2 registers.
configs CPU_GICH_LR_COUNT=4U

# The number of implemented ICH_APR[01]R<n>_EL2 registers.
configs CPU_GICH_APR_COUNT=1U

# The number of implemented DBGB[CV]R_EL1 (HW breakpoint) registers.
configs CPU_DEBUG_BP_COUNT=6U

# The number of implemented DBGW[CV]R_EL1 (HW watchpoint) registers.
configs CPU_DEBUG_WP_COUNT=4U

# The level of support for ARMv8.4-TTRem on this CPU (encoded the same way
# as ID_AA64MMFR2_EL1.BBM).
configs CPU_PGTABLE_BBM_LEVEL=2U
includes
