# Copyright © Qualcomm Technologies, Inc. and/or its subsidiaries.
#
# SPDX-License-Identifier: BSD-3-Clause

base_arch armv8-64
flags -mcpu=neoverse-v1
flags -mbranch-protection=pac-ret

configs ARCH_AARCH64_32BIT_EL0=1
configs ARCH_AARCH64_32BIT_EL0_ALL_CORES=0
configs ARCH_AARCH64_32BIT_EL1=0
configs ARCH_AARCH64_BIG_END_ALL_CORES=1

configs ARCH_CORE_IDS=NEOVERSE_V1
configs ARCH_ARM_PMU_HPMN_UNPREDICTABLE=1

# Optional architecture extensions in v8.0
configs ARCH_ARM_FEAT_SHA1=1
configs ARCH_ARM_FEAT_AES=1
configs ARCH_ARM_FEAT_PMULL=1

# Mandatory architecture extensions in v8.1
configs ARCH_ARM_FEAT_HPDS=1
configs ARCH_ARM_FEAT_LSE=1
configs ARCH_ARM_FEAT_LOR=1
configs ARCH_ARM_FEAT_PAN=1
configs ARCH_ARM_FEAT_RDM=1
configs ARCH_ARM_FEAT_VHE=1
configs ARCH_ARM_FEAT_CRC32=1

# Optional architecture extensions in v8.1
configs ARCH_ARM_FEAT_HAFDBS=1
configs ARCH_ARM_FEAT_VMID16=1
configs ARCH_ARM_FEAT_PMUv3p1=1
configs ARCH_ARM_PMU_VER=3

# Mandatory architecture extensions in v8.2
configs ARCH_ARM_FEAT_ASMv8p2=1
configs ARCH_ARM_FEAT_PAN2=1
configs ARCH_ARM_FEAT_FHM=1
configs ARCH_ARM_FEAT_DotProd=1
configs ARCH_ARM_FEAT_UAO=1
configs ARCH_ARM_FEAT_DPB=1
configs ARCH_ARM_FEAT_DPB2=1
configs ARCH_ARM_FEAT_TTCNP=1
configs ARCH_ARM_FEAT_XNX=1
configs ARCH_ARM_FEAT_IESB=1
configs ARCH_ARM_FEAT_RAS=1
configs ARCH_ARM_FEAT_DEBUGv8p2=1

# Optional architecture extensions in v8.2
configs ARCH_ARM_FEAT_FP16=1
configs ARCH_ARM_FEAT_HPDS2=1
configs ARCH_ARM_FEAT_SHA3=1
configs ARCH_ARM_FEAT_SHA512=1
configs ARCH_ARM_FEAT_SM3=1
configs ARCH_ARM_FEAT_SM4=1
configs ARCH_ARM_FEAT_EVT=1

# Mandatory architecture extensions in v8.3
configs ARCH_ARM_FEAT_FCMA=1
configs ARCH_ARM_FEAT_JSCVT=1
configs ARCH_ARM_FEAT_LRCPC=1
configs ARCH_ARM_FEAT_PAuth=1
configs ARCH_ARM_FEAT_EPAC=1
configs ARCH_ARM_FEAT_FPAC=1

# Optional architecture extensions in v8.3
configs ARCH_ARM_FEAT_CCIDX=1
configs ARCH_ARM_FEAT_DoPD=1
configs ARCH_ARM_FEAT_SPEv1p1=1

# Mandatory architecture extensions in v8.4
configs ARCH_ARM_FEAT_DIT=1
configs ARCH_ARM_FEAT_FlagM=1
configs ARCH_ARM_FEAT_LRCPC2=1
configs ARCH_ARM_FEAT_LSE2=1
configs ARCH_ARM_FEAT_TTL=1
configs ARCH_ARM_FEAT_S2FWB=1
configs ARCH_ARM_FEAT_IDST=1
configs ARCH_ARM_FEAT_DEBUGv8p4=1
configs ARCH_ARM_FEAT_TRF=1
configs ARCH_ARM_FEAT_PMUv3p4=1
configs ARCH_ARM_FEAT_RASv1p1=1
configs ARCH_ARM_FEAT_DoubleFault=1
configs ARCH_ARM_FEAT_AMUv1=1
configs ARCH_ARM_FEAT_BBM=1

# Architecture extensions that are either directly mandatory in v8.4, or
# mandatory as dependencies of other features in v8.4, but nevertheless are
# not implemented by Neoverse-V1.
#configs ARCH_ARM_FEAT_TLBIOS=1
#configs ARCH_ARM_FEAT_TLBIRANGE=1
#configs ARCH_ARM_FEAT_TTST=1
#configs ARCH_ARM_FEAT_SEL2=1

# Optional architecture extensions in v8.4
# (none implemented)

# Optional architecture extensions in v8.5
configs ARCH_ARM_FEAT_RNG=1
configs ARCH_ARM_FEAT_SPE=1

configs VGIC_HAS_EXT_SPIS=1
configs VGIC_HAS_EXT_PPIS=0

# The number of implemented ICH_LR<n>_EL2 registers.
configs CPU_GICH_LR_COUNT=4U

# The number of implemented ICH_APR[01]R<n>_EL2 registers.
configs CPU_GICH_APR_COUNT=1U

# The number of implemented DBGB[CV]R_EL1 (HW breakpoint) registers.
configs CPU_DEBUG_BP_COUNT=6U

# The number of implemented DBGW[CV]R_EL1 (HW watchpoint) registers.
configs CPU_DEBUG_WP_COUNT=4U

# The level of support for ARMv8.4-TTRem on this CPU (encoded the same way
# as ID_AA64MMFR2_EL1.BBM).
configs CPU_PGTABLE_BBM_LEVEL=2U

# MPAM Version1.0
configs ARCH_ARM_FEAT_MPAM=1
includes
