# Copyright © Qualcomm Technologies, Inc. and/or its subsidiaries.
#
# SPDX-License-Identifier: BSD-3-Clause

base_arch oryon-ncc

flags -march=armv8.7-a+memtag
flags -mtune=cortex-x1
# BTI and PAuth are mandatory in v8.5+, so tell the compiler to use them
flags -mbranch-protection=bti+pac-ret

# R1 and R1.1 don't support ECBHB or CLRBHB, but are not in production
configs ARCH_ARM_FEAT_CLRBHB=1
configs ARCH_ARM_FEAT_ECBHB=1

# These CPUs always have an ETM (but events can be filtered with FEAT_TRF).
configs PLATFORM_HAS_NO_ETM_BASE=0

includes
