# Copyright © Qualcomm Technologies, Inc. and/or its subsidiaries.
#
# SPDX-License-Identifier: BSD-3-Clause

configs PLATFORM_SECURE_HYP_ARCH_VIRTUAL_TIMER_IRQ=19
configs PLATFORM_SECURE_HYP_ARCH_PHYSICAL_TIMER_IRQ=20
configs PLATFORM_STATISTICAL_PROFILING_IRQ=21
configs PLATFORM_DEBUG_COMMS_CHANNEL_IRQ=22
configs PLATFORM_PMU_IRQ=23
configs PLATFORM_CTI_IRQ=24
configs PLATFORM_GICH_IRQ=25
configs PLATFORM_HYP_ARCH_PHYSICAL_TIMER_IRQ=26
configs PLATFORM_VM_ARCH_VIRTUAL_TIMER_IRQ=27
configs PLATFORM_HYP_ARCH_VIRTUAL_TIMER_IRQ=28
configs PLATFORM_SECURE_ARCH_PHYSICAL_TIMER_IRQ=29
configs PLATFORM_VM_ARCH_PHYSICAL_TIMER_IRQ=30

# Backwards compat
configs PLATFORM_HYP_ARCH_TIMER_IRQ=PLATFORM_HYP_ARCH_PHYSICAL_TIMER_IRQ

# Non-SBSA PPIs, platform reserved, usable for other purposes
configs PLATFORM_SBSA_PPI_RESERVED_1=16
