# Copyright © Qualcomm Technologies, Inc. and/or its subsidiaries.
#
# SPDX-License-Identifier: BSD-3-Clause

local_include
base_module hyp/mem/useraccess
base_module hyp/vm/virtio

types virtio_virtq.tc
source virtio_virtq.c
