# Copyright © Qualcomm Technologies, Inc. and/or its subsidiaries.
#
# SPDX-License-Identifier: BSD-3-Clause

interface vpci
interface pci
local_include
types vpci.tc
events vpci.ev
source vpci.c host_bridge.c hypercalls.c mapping.c msix.c pcie.c vdevice.c virq.c
configs VIC_VIRTUAL_MSI=1
configs VPCI_PCIE_ONLY=1
configs VPCI_MULTI_FUNCTION=0
