# Copyright © Qualcomm Technologies, Inc. and/or its subsidiaries.
#
# SPDX-License-Identifier: BSD-3-Clause

interface trace
events trace.ev
local_include
source trace.c hypercalls.c
source debug.S
types trace.tc
