# Copyright © Qualcomm Technologies, Inc. and/or its subsidiaries.
#
# SPDX-License-Identifier: BSD-3-Clause

arch_types aarch64 types.tc
arch_template registers aarch64 hypregisters.h
arch_registers aarch64 registers.reg

arch_source aarch64 asm_ordering.c atomic.c nospec_checks.c
arch_source aarch64 interrupt.c
arch_source cortex-a-v8_2 sysreg_init.c
arch_events cortex-a-v8_2 sysreg_init.ev
arch_source cortex-a-v9 sysreg_init.c
arch_events cortex-a-v9 sysreg_init.ev
arch_source neoverse-v1 sysreg_init.c
arch_events neoverse-v1 sysreg_init.ev
