// © 2021 Qualcomm Innovation Center, Inc. All rights reserved.
//
// 2019 Cog Systems Pty Ltd.
//
// SPDX-License-Identifier: BSD-3-Clause
// This file is automatically generated.

#include <hyptypes.h>

#include <compiler.h>
#include <includefile.h>

#include <events/basic_event_features_interface.h>

void
test_simple_event_handler(void);

void
basic_event_features_module_handle_basic_event_features_interface_priority_max_event(
	void);

void
basic_event_features_module_handle_basic_event_features_interface_priority_min_event(
	void);

void
basic_event_features_module_handle_basic_event_features_interface_priority_default_event(
	void);

noreturn void
test_noreturn_handler(void);

void
basic_event_features_module_handle_basic_event_features_interface_require_lock_event(
	void) REQUIRE_LOCK((lock));

void
basic_event_features_module_handle_basic_event_features_interface_acquire_lock_event(
	void) ACQUIRE_LOCK((lock));

void
basic_event_features_module_handle_basic_event_features_interface_exclude_lock_event(
	void) EXCLUDE_LOCK((lock));

void
basic_event_features_module_handle_basic_event_features_interface_release_lock_event(
	void) RELEASE_LOCK((lock));

void
basic_event_features_module_handle_basic_event_features_interface_require_read_event(
	void) REQUIRE_READ((lock));

void
handle_acquire_release_2(void) RELEASE_LOCK((lock2));

void
handle_acquire_release_1(void) ACQUIRE_LOCK((lock2));

void
handle_release_acquire_2(void) ACQUIRE_LOCK((lock));

void
handle_release_acquire_1(void) RELEASE_LOCK((lock));

void
basic_event_features_module_handle_basic_event_features_interface_parameterized_event(
	void);

error_t
test_selector_event_handler(uint32_t param0, uint32_t param1);

error_t
basic_event_features_module_handle_basic_event_features_interface_selector_event(
	hwirq_action_t action, uint32_t param0, uint32_t param1);

error_t
basic_event_features_module_handle_basic_event_features_interface_selector_with_lock(
	hwirq_action_t action, uint32_t param0, uint32_t param1)
	RELEASE_LOCK((lock));

error_t
test_handled_event_handler(cap_id_t param0, index_t param1);

int32_t
basic_event_features_module_handle_basic_event_features_interface_multi_event(
	int32_t count_param, cap_id_t param0, index_t param1);

error_t
basic_event_features_module_handle_basic_event_features_interface_setup_event(
	uintptr_t param0, uintptr_t param1);

void
basic_event_features_module_unwind_basic_event_features_interface_setup_event(
	error_t result, uintptr_t param0, uintptr_t param1);

error_t
basic_event_features_module_handle_basic_event_features_interface_setup_with_unwinders(
	uintptr_t param0, uintptr_t param1) ACQUIRE_LOCK((lock));

void
setup_event_unwinder1(void) RELEASE_LOCK((lock));

void
setup_event_unwinder2(void) ACQUIRE_LOCK((lock));

void
setup_event_unwinder3(void) EXCLUDE_LOCK((lock));

void
trigger_basic_event_features_interface_simple_event_event(void)
{
	test_simple_event_handler();
}

void
trigger_basic_event_features_interface_priority_max_event_event(void)
{
	basic_event_features_module_handle_basic_event_features_interface_priority_max_event();
}

void
trigger_basic_event_features_interface_priority_min_event_event(void)
{
	basic_event_features_module_handle_basic_event_features_interface_priority_min_event();
}

void
trigger_basic_event_features_interface_priority_default_event_event(void)
{
	basic_event_features_module_handle_basic_event_features_interface_priority_default_event();
}

noreturn void
trigger_basic_event_features_interface_noreturn_event_event(void)
{
	test_noreturn_handler();
}

void
trigger_basic_event_features_interface_require_lock_event_event(void)
{
	basic_event_features_module_handle_basic_event_features_interface_require_lock_event();
}

void
trigger_basic_event_features_interface_acquire_lock_event_event(void)
{
	basic_event_features_module_handle_basic_event_features_interface_acquire_lock_event();
}

void
trigger_basic_event_features_interface_exclude_lock_event_event(void)
{
	basic_event_features_module_handle_basic_event_features_interface_exclude_lock_event();
}

void
trigger_basic_event_features_interface_release_lock_event_event(void)
{
	basic_event_features_module_handle_basic_event_features_interface_release_lock_event();
}

void
trigger_basic_event_features_interface_require_read_event_event(void)
{
	basic_event_features_module_handle_basic_event_features_interface_require_read_event();
}

void
trigger_basic_event_features_interface_lock_ordering_event_event(void)
{
	handle_acquire_release_2();
	handle_acquire_release_1();
	handle_release_acquire_2();
	handle_release_acquire_1();
}

void
trigger_basic_event_features_interface_parameterized_event_event(
	abort_reason_t reason)
{
	(void)reason;
	basic_event_features_module_handle_basic_event_features_interface_parameterized_event();
}

error_t
trigger_basic_event_features_interface_handled_event_event(cap_id_t param0,
							   index_t  param1)
{
	error_t ret;

	ret = test_handled_event_handler(param0, param1);
	if (ret != ERROR_CSPACE_WRONG_OBJECT_TYPE) {
		goto out;
	}

out:
	return ret;
}

int32_t
trigger_basic_event_features_interface_multi_event_event(int32_t  count_param,
							 cap_id_t param0,
							 index_t  param1)
{
	int32_t _ret;
	_ret = basic_event_features_module_handle_basic_event_features_interface_multi_event(
		count_param, param0, param1);
	if (_ret >= count_param) {
		return (int32_t)0;
	}
	count_param -= _ret;
	_ret = test_multi_event_handler(param0);
	if (_ret >= count_param) {
		return (int32_t)0;
	}
	count_param -= _ret;
	return count_param;
}

error_t
trigger_basic_event_features_interface_setup_event_event(uintptr_t param0,
							 uintptr_t param1)
{
	error_t result = ERROR_FAILURE;

	result =
		basic_event_features_module_handle_basic_event_features_interface_setup_event(
			param0, param1);

	return result;
}

error_t
trigger_basic_event_features_interface_setup_with_unwinders_event(
	uintptr_t param0, uintptr_t param1)
{
	error_t result = ERROR_FAILURE;

	result =
		basic_event_features_module_handle_basic_event_features_interface_setup_with_unwinders(
			param0, param1);
	if (compiler_expected(result == OK)) {
		result =
			basic_event_features_module_handle_basic_event_features_interface_setup_with_unwinders(
				param0, param1);
		if (compiler_expected(result == OK)) {
			result =
				basic_event_features_module_handle_basic_event_features_interface_setup_with_unwinders(
					param0, param1);

			if (compiler_unexpected(result != OK)) {
				setup_event_unwinder2();
			}
		}
		if (compiler_unexpected(result != OK)) {
			setup_event_unwinder1();
		}
	}

	return result;
}

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wswitch-enum"

error_t
trigger_basic_event_features_interface_selector_event_event(
	hwirq_action_t action, uint32_t param0, uint32_t param1)
{
	error_t ret;
	switch (action) {
	case SELECTOR_1:
		ret = test_selector_event_handler(param0, param1);
		break;
	case SELECTOR_2:
		ret = basic_event_features_module_handle_basic_event_features_interface_selector_event(
			action, param0, param1);
		break;
	case SELECTOR_3:
		ret = basic_event_features_module_handle_basic_event_features_interface_selector_event(
			action, param0, param1);
		break;
	case SELECTOR_4:
		ret = OK;
		break;
	default:
		ret = ERROR_ARGUMENT_INVALID;
		break;
	}

	return ret;
}

#pragma clang diagnostic pop

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wswitch-enum"

error_t
trigger_basic_event_features_interface_selector_with_lock_event(
	hwirq_action_t action, uint32_t param0, uint32_t param1)
{
	error_t ret;
	switch (action) {
	case SELECTOR_1:
		ret = basic_event_features_module_handle_basic_event_features_interface_selector_with_lock(
			action, param0, param1);
		break;
	case SELECTOR_2:
		ret = basic_event_features_module_handle_basic_event_features_interface_selector_with_lock(
			action, param0, param1);
		break;
	default:
		ret = ERROR_ARGUMENT_INVALID;
		break;
	}

	return ret;
}

#pragma clang diagnostic pop

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wswitch-enum"

void
trigger_basic_event_features_interface_selector_void_return_event(
	uint32_t param0)
{
	// No subscribers
	(void)param0;
}

#pragma clang diagnostic pop
