// Copyright © Qualcomm Technologies, Inc. and/or its subsidiaries.
//
// 2019 Cog Systems Pty Ltd.
//
// SPDX-License-Identifier: BSD-3-Clause
// This file is automatically generated.

#ifndef HANDLERS_BASIC_EVENT_FEATURES_MODULE_H_
#define HANDLERS_BASIC_EVENT_FEATURES_MODULE_H_

void
test_simple_event_handler(void);

void
basic_event_features_module_handle_basic_event_features_interface_priority_max_event(
	void);

void
basic_event_features_module_handle_basic_event_features_interface_priority_min_event(
	void);

void
basic_event_features_module_handle_basic_event_features_interface_priority_default_event(
	void);

noreturn void
test_noreturn_handler(void);

void
basic_event_features_module_handle_basic_event_features_interface_require_lock_event(
	void) REQUIRE_LOCK((lock));

void
basic_event_features_module_handle_basic_event_features_interface_acquire_lock_event(
	void) ACQUIRE_LOCK((lock));

void
basic_event_features_module_handle_basic_event_features_interface_exclude_lock_event(
	void) EXCLUDE_LOCK((lock));

void
basic_event_features_module_handle_basic_event_features_interface_release_lock_event(
	void) RELEASE_LOCK((lock));

void
basic_event_features_module_handle_basic_event_features_interface_require_read_event(
	void) REQUIRE_READ((lock));

void
handle_release_acquire_1(void) RELEASE_LOCK((lock));

void
handle_release_acquire_2(void) ACQUIRE_LOCK((lock));

void
handle_acquire_release_1(void) ACQUIRE_LOCK((lock2));

void
handle_acquire_release_2(void) RELEASE_LOCK((lock2));

void
basic_event_features_module_handle_basic_event_features_interface_parameterized_event(
	void);

error_t
test_selector_event_handler(uint32_t param0, uint32_t param1);

error_t
basic_event_features_module_handle_basic_event_features_interface_selector_event(
	hwirq_action_t action, uint32_t param0, uint32_t param1);

error_t
basic_event_features_module_handle_basic_event_features_interface_selector_with_lock(
	hwirq_action_t action, uint32_t param0, uint32_t param1)
	RELEASE_LOCK((lock));

error_t
test_handled_event_handler(cap_id_t param0, index_t param1);

int32_t
basic_event_features_module_handle_basic_event_features_interface_multi_event(
	int32_t count_param, cap_id_t param0, index_t param1);

error_t
basic_event_features_module_handle_basic_event_features_interface_setup_event(
	uintptr_t param0, uintptr_t param1);

void
basic_event_features_module_unwind_basic_event_features_interface_setup_event(
	error_t result, uintptr_t param0, uintptr_t param1);

error_t
basic_event_features_module_handle_basic_event_features_interface_setup_with_unwinders(
	uintptr_t param0, uintptr_t param1) ACQUIRE_LOCK((lock));

void
setup_event_unwinder1(void) RELEASE_LOCK((lock));

void
setup_event_unwinder2(void) ACQUIRE_LOCK((lock));

void
setup_event_unwinder3(void) EXCLUDE_LOCK((lock));

#else
#error multiple include
#endif
