// Copyright © Qualcomm Technologies, Inc. and/or its subsidiaries.
//
// 2019 Cog Systems Pty Ltd.
//
// SPDX-License-Identifier: BSD-3-Clause
// This file is automatically generated.

void
trigger_basic_event_features_interface_simple_event_event(void);

void
trigger_basic_event_features_interface_priority_max_event_event(void);

void
trigger_basic_event_features_interface_priority_min_event_event(void);

void
trigger_basic_event_features_interface_priority_default_event_event(void);

noreturn void
trigger_basic_event_features_interface_noreturn_event_event(void);

void
trigger_basic_event_features_interface_require_lock_event_event(void)
	REQUIRE_LOCK((lock));

void
trigger_basic_event_features_interface_acquire_lock_event_event(void)
	ACQUIRE_LOCK((lock)) EXCLUDE_LOCK((lock));

void
trigger_basic_event_features_interface_exclude_lock_event_event(void)
	EXCLUDE_LOCK((lock));

void
trigger_basic_event_features_interface_release_lock_event_event(void)
	RELEASE_LOCK((lock)) REQUIRE_LOCK((lock));

void
trigger_basic_event_features_interface_require_read_event_event(void)
	REQUIRE_READ((lock));

void
trigger_basic_event_features_interface_lock_ordering_event_event(void)
	EXCLUDE_LOCK((lock)) REQUIRE_LOCK((lock2));

void
trigger_basic_event_features_interface_parameterized_event_event(
	abort_reason_t reason);

error_t
trigger_basic_event_features_interface_selector_event_event(
	hwirq_action_t action, uint32_t param0, uint32_t param1);

error_t
trigger_basic_event_features_interface_selector_with_lock_event(
	hwirq_action_t action, uint32_t param0, uint32_t param1)
	RELEASE_LOCK((lock)) RELEASE_LOCK((lock2));

void
trigger_basic_event_features_interface_selector_void_return_event(
	uint32_t param0);

error_t
trigger_basic_event_features_interface_handled_event_event(cap_id_t param0,
							   index_t  param1);

int32_t
trigger_basic_event_features_interface_multi_event_event(int32_t  count_param,
							 cap_id_t param0,
							 index_t  param1);

error_t
trigger_basic_event_features_interface_setup_event_event(uintptr_t param0,
							 uintptr_t param1);

error_t
trigger_basic_event_features_interface_setup_with_unwinders_event(
	uintptr_t param0, uintptr_t param1) EXCLUDE_LOCK((lock));
