# © 2024 Qualcomm Innovation Center, Inc. All rights reserved.
#
# SPDX-License-Identifier: BSD-3-Clause

# ARM FVP RD-V1 config, based on Juno dev platform

interface platform

base_module hyp/platform/gicv3
base_module hyp/platform/psci_smc

configs BOOT_STACK_SIZE=6144
configs PLATFORM_DEBUG_SAVE_STATE=0

local_include
types fvp.tc
source head.S boot.c soc_fvp.c irq.c cpu.c cpu_features.c uart.c
source abort.c platform_psci.c addrspace.c prng.c memory_layout.c
source msi.c

events fvp.ev
