# Copyright © Qualcomm Technologies, Inc. and/or its subsidiaries.
#
# SPDX-License-Identifier: BSD-3-Clause

arch_source qemu-armv8-5a-rng sysreg_traps_cpu.c
arch_source qemu-armv8-5a-rng context_switch.c
