# Copyright © Qualcomm Technologies, Inc. and/or its subsidiaries.
#
# SPDX-License-Identifier: BSD-3-Clause

interface rootvm
events rootvm.ev
types rootvm.tc
base_module hyp/core/boot
base_module hyp/vm/vpm_base
source rootvm_init.c
