# Copyright © Qualcomm Technologies, Inc. and/or its subsidiaries.
#
# SPDX-License-Identifier: BSD-3-Clause

interface virtio_pci
base_module hyp/vm/virtio
types virtio_pci.tc
events virtio_pci.ev
source virtio_pci.c vdevice.c
