# © 2021 Qualcomm Innovation Center, Inc. All rights reserved.
#
# SPDX-License-Identifier: BSD-3-Clause

local_include
base_module hyp/vm/vgic
base_module hyp/vm/vic_base
base_module hyp/mem/useraccess
base_module hyp/platform/gicv3
first_class_object vgic_its no_partition_create_hypcall
configs VGIC_HAS_ITS=1
# Ensure that the physical ITS driver maps enough event IDs for every device
configs GICV3_ITS_EVENT_BITS=VGIC_ITS_EVENT_BITS
types vgic_its.tc
events vgic_its.ev
source commands.c tables.c vdevice.c vits.c
