# Copyright © Qualcomm Technologies, Inc. and/or its subsidiaries.
#
# SPDX-License-Identifier: BSD-3-Clause

local_include
base_module hyp/platform/gicv3
types smmuv3_cmd.tc smmuv3_event.tc smmuv3_stream_table.tc smmuv3_context_desc.tc smmuv3.tc
events smmuv3.ev
source smmuv3.c
first_class_object smmuv3 no_partition_create_hypcall

# SMMUv3 TCU config uses at least two consecutive 64k pages
configs SMMU_V3_PAGE_SIZE=65536
