# © 2024 Qualcomm Innovation Center, Inc. All rights reserved.
#
# SPDX-License-Identifier: BSD-3-Clause

local_include
types smmuv3.tc
events smmuv3.ev
source smmuv3.c

# SMMUv3 TCU config uses at least two consecutive 64k pages
configs SMMU_V3_PAGE_SIZE=65536
