# Copyright © Qualcomm Technologies, Inc. and/or its subsidiaries.
#
# SPDX-License-Identifier: BSD-3-Clause

types memextent.tc
events memextent.ev
first_class_object memextent
hypercalls memextent.hvc
includes
