# Copyright © Qualcomm Technologies, Inc. and/or its subsidiaries.
#
# SPDX-License-Identifier: BSD-3-Clause

first_class_object watchdog
hypercalls watchdog.hvc
types watchdog.tc
events watchdog.ev
includes
