# Copyright © Qualcomm Technologies, Inc. and/or its subsidiaries.
#
# SPDX-License-Identifier: BSD-3-Clause

base_module hyp/mem/useraccess
interface partition
events partition.ev
types partition.tc
source init.c partition.c
template first_class_object object.ev object.tc object.c hypercalls.c
arch_source armv8 phys_access.c
arch_events armv8 phys_access.ev
source hypercalls.c
hypercalls hypercalls.hvc
